version: '2.2'
services:
  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://127.0.0.1:3000
      - GF_SECURITY_ADMIN_PASSWORD=123456
    ports:
      - 3000:3000
    networks:
      - local-net
    external_links:
      - local-net
networks:
  local-net:
    external: true